# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "chef/ubuntu-14.04"

  config.vm.network "forwarded_port", guest: 80, host: 8006

  config.vm.network "private_network", ip: "192.168.33.31"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.network :private_network, ip: "192.168.33.31", :netmask => "255.255.255.0"

  config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      # vagrant provision shall deploy only on hosts from the group vagrant
      ansible.limit = "vagrant"
      ansible.playbook = "vagrant_provision/ansible/playbook.yml"
      ansible.inventory_path = "vagrant_provision/ansible/inventory/vagrant"
      ansible.extra_vars = {
#            encoding_key: "YOLO"
      }
  end

end
