---
- name: Install zsh
  apt: pkg=zsh state=latest

- name: Copy zsh config
  sudo: false
  copy: src=zshrc.template dest=~/.zshrc

- name: Checkout oh my zsh
  sudo: false
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh accept_hostkey=true
